### ISSUE TITLE
[SUGGEST] Add DKIM keys

### ISSUE THREAD

**Issue by duhow** [ivantcholakov/codeigniter-phpmailer#11]
Add a function to setup DKIM keys directly. http://stackoverflow.com/a/24464694

**Comment by ivantcholakov** [comment]
Probably I will do this when PHPMailer 5.2.15 gets released.

**Comment by ivantcholakov** [comment]
https://github.com/bcit-ci/CodeIgniter/issues/3626

**Comment by ivantcholakov** [comment]
https://github.com/PHPMailer/PHPMailer/issues/637

**Comment by duhow** [comment]
I used this code until it gets developed:
```php
$this->email
	->set_header('Precedence', 'bulk')
	->set_header('Auto-Submitted', 'auto-generated')
// ............

$this->email->phpmailer->DKIM_domain = 'example.com';
$this->email->phpmailer->DKIM_private = '/etc/apache2/ssl/dkim.key';
$this->email->phpmailer->DKIM_selector = '1234567890.example';

$this->email->send();
```

**Comment by ivantcholakov** [comment]
@duhow

The problem is that CodeIgniter will solve this and probably the email API and the configuration setting will be extended. If I do this before them, I would create something different, and mess is going to happen that lately should be cleaned.

I will wait for PHPMailer 5.2.15 and then I will decide what to do. Thank you for your snippet of code, it would be useful meanwhile.

**Comment by ivantcholakov** [comment]
v1.2.0

**Comment by ivantcholakov** [comment]
https://github.com/ivantcholakov/codeigniter-phpmailer/commit/da1918c63325946e8cbf52e2f2c26900b7533718
